version: '3.6'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    tty: true

  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    depends_on:
      - rabbitmq
    env_file:
      - setup/secrets/.env
    tty: true

  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    depends_on:
      - consumer
    env_file:
      - setup/secrets/.env
    tty: true

  ai:
    build:
      context: .
      dockerfile: Dockerfile_ai
    depends_on:
      - consumer
    env_file:
      - setup/secrets/.env
    tty: true
