# ---|DOCKERFILE|---

#................................................................
# ---|BUILDER|---
#................................................................
FROM python:3.10

WORKDIR /producer

#................................................................
# ---|INSTALLATION|---
#................................................................
COPY project/producer/requirements.txt ./producer/

RUN apt-get update && \
  apt-get install -y curl

RUN python -m pip install --upgrade pip

RUN apt-get update && \
  apt-get upgrade -y && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install -y libgl1-mesa-glx

RUN pip install --no-cache-dir -r ./producer/requirements.txt

#................................................................
# ---|DEPENDENCIES|---
#................................................................
COPY setup/config ./producer/config

COPY setup/libs/consumer_producer ./producer/packages

#................................................................
# ---|OTHERS FILES|---
#................................................................
COPY project/producer ./producer/

#________________________________________________________________
# CMD
#________________________________________________________________

CMD ["python", "producer/__main__.py"]
