version: '3.3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  firmware:
    build:
      context: ./project/firmware
    ports:
      - "3000:3000"
    image: "mimir/firmware:0.0.1"
    working_dir: /firmware
