version: '3.6'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    tty: true

  firmware-consumer:
    build:
      context: ./project/firmware/consumer
    ports:
      - "4000:4000"
    image: "mimir/firmware-consumer:0.1.0"
    working_dir: /firmware-consumer
    depends_on:
      - rabbitmq
    tty: true

  firmware-producer:
    build:
      context: ./project/firmware/producer
    ports:
      - "3000:3000"
    image: "mimir/firmware-producer:0.1.0"
    working_dir: /firmware-producer
    depends_on:
      - firmware-consumer
    tty: true
