# ---|DOCKERFILE|---

#................................................................
# ---|BUILDER|---
#................................................................
FROM python:3.10

WORKDIR /consumer

#................................................................
# ---|INSTALLATION|---
#................................................................
COPY project/consumer/requirements.txt ./consumer/

RUN apt-get update && \
  apt-get install -y curl

RUN python -m pip install --upgrade pip

RUN apt-get update && \
  apt-get upgrade -y && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install -y libgl1-mesa-glx

RUN pip install --no-cache-dir -r ./consumer/requirements.txt

#................................................................
# ---|DEPENDENCIES|---
#................................................................
COPY setup/config ./consumer/config

COPY setup/libs/consumer_producer ./consumer/packages

#................................................................
# ---|OTHERS FILES|---
#................................................................
COPY project/consumer ./consumer/

#________________________________________________________________
# CMD
#________________________________________________________________

CMD ["python", "consumer/__main__.py"]
