version: '3.6'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    tty: true

  #mimir:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - rabbitmq
  #  env_file:
  #    - settings/secrets/.env
  #  tty: true
